LF-Engineering/insights-datasource-shared

aws/s3/s3.go
aws/ssm/parameters.go

add aws ssm & s3 libraries

---

datasourceStatus/client.go
datasourceStatus/dto.go

Signed-off-by: “khalifapro” <enkhalifapro@yahoo.com>

Add datasource status

---

Makefile
firehose/firehose.go
go.mod
go.sum
uuid.go
uuid/uuid.go
uuid/uuid.py
uuid/uuid_test.go

Implement kinesis firehose wrapper with chunks

---

slack/slack.go
slack/slack_test.go

add slack library

---

firehose/firehose.go

Signed-off-by: linonymous <linonymous@gmail.com>

Fix firehose response creation

---

deploy/main.tf
deploy/variables.tf

Signed-off-by: linonymous <iamlinonymous@gmail.com>

ECS terraform Deployment

---

deploy/main.tf

Signed-off-by: Ajinkya Nahar <ajinkyan@proximabiz.com>

DA-4648: add jira connector ecs task terraform configuration

---

deploy/main.tf

DA-4653: add gerrit connector task definition

---

deploy/dev/main.tf
deploy/prod/main.tf
deploy/test/main.tf

- add service for jira & gerrit
Signed-off-by: linonymous <iamlinonymous@gmail.com>

Add up github task & service

---

deploy/dev/main.tf
deploy/prod/main.tf
deploy/test/main.tf

Update image region and desired count

---

deploy/dev/main.tf
deploy/prod/main.tf
deploy/test/main.tf

Add bugzillarest task definition and service

---

deploy/dev/main.tf
deploy/prod/main.tf
deploy/test/main.tf

Add dockerhub task definition and service

---

cryptography/encrypt.go

Signed-off-by: Ikoh Obaro <obaro.ikohpgs@stu.cu.edu.ng>

Add encryption/decryption functionality

---

deploy/README.md
deploy/dev/main.tf
deploy/prod/main.tf
deploy/test/main.tf

Signed-off-by: linonymous <iamlinonymous@gmail.com>

Update the terraform path & add readme

---

deploy/dev/main.tf
deploy/prod/main.tf
deploy/test/main.tf

Signed-off-by: Obaro Ikoh <obaroikohb@gmail.com>

Add ecs for jenkins, circleci and rocketchat

---

cryptography/encrypt.go

Signed-off-by: Ikoh Obaro <obaro.ikohpgs@stu.cu.edu.ng>

Update encryption inplementation

---

deploy/dev/main.tf

Signed-off-by: Ikoh Obaro <obaro.ikohpgs@stu.cu.edu.ng>

Update ECS task role

---

deploy/dev/main.tf
deploy/prod/main.tf
deploy/test/main.tf

Add circleci, confluence, rocketChat and Jenkins ecs services

---

context.go
es.go

Adds support for non-incremental mode (will do a full sync, will not record last update date in ES cache).
cc @fayazg @1010sachin @priyankakale15 
Signed-off-by: Łukasz Gryglicki <lgryglicki@cncf.io>

Support no incremental flag

---

.circleci/config.yml
deploy/dev/main.tf
deploy/dev/variables.tf
deploy/prod/main.tf
deploy/prod/variables.tf
deploy/test/main.tf
deploy/test/variables.tf

Remove hardcoded aws account id from terraform

---

deploy/dev/main.tf

Signed-off-by: Łukasz Gryglicki <lgryglicki@cncf.io>

Add groups.io task definition

---

deploy/dev/main.tf

use account id variable

---

Makefile
firehose/firehose.go
ingestjob/logger.go
log.go

Signed-off-by: Łukasz Gryglicki <lgryglicki@cncf.io>

Add logging on shared.Prtintf calls

---

deploy/dev/main.tf

Update task permissions

---

ingestjob/dto.go
ingestjob/logger.go

add function to write ecs tasks

---

ingestjob/logger.go

Update ingestjob logging connector tasks

---

ingestjob/logger.go

Enhance write task id

---

deploy/dev/main.tf

DA-4875: fix pipermail cpu size

---

deploy/dev/main.tf

Signed-off-by: Fayaz G <5818912+fayazg@users.noreply.github.com>

add mailling list services

---

deploy/dev/main.tf

Features added:
- enhance scheduler logging

Enhance scheduler logging

---

deploy/dev/main.tf

Fix typo error

---

deploy/dev/main.tf

Features added:
- Add policy to enable get ssm parameters and attach it to ecs-task-role

Add policy to enable ssm get parameters

---

deploy/prod/main.tf

Fixing:
- add missing task definitions and other sources for prod environment

Update terraform for prod environment

---

.circleci/config.yml
.gitignore
deploy/dev/main.tf
deploy/prod/main.tf

Update terraform dev configurations

---

deploy/dev/main.tf
deploy/prod/main.tf

Getting out of memory issues on this connector so doubling the size
Signed-off-by: Fayaz G <5818912+fayazg@users.noreply.github.com>

double memory of github connector

---

deploy/dev/main.tf
deploy/prod/main.tf

Increase git connector memory

---

deploy/dev/main.tf
deploy/prod/main.tf

Signed-off-by: Ibrahim Mbaziira <dev.code.ibra@gmail.com>

add repositories association task definition

---

deploy/dev/main.tf
deploy/prod/main.tf

Increase git connector cpu

---

http/client.go

Signed-off-by: Ibrahim Mbaziira <dev.code.ibra@gmail.com>

handle redirects

---

.circleci/config.yml
deploy/dev/main.tf
deploy/prod/main.tf

Trigger scheduler using cron event

---

deploy/dev/main.tf
deploy/prod/main.tf

Update cron rule

---

deploy/dev/main.tf
deploy/prod/main.tf

Revert scheduler cron changes

---

deploy/dev/main.tf
deploy/prod/main.tf

Signed-off-by: Ibrahim Mbaziira <dev.code.ibra@gmail.com>

increase github container memory

---

ingestjob/logger.go

Update log message

---

ingestjob/dto.go
ingestjob/logger.go

Enhance ingestjob log

---

deploy/dev/main.tf
deploy/prod/main.tf

Add cluster name to scheduler task

---

elastic/client.go
ingestjob/logger.go

Add elastic get backoff

---

utils.go

Add is bot identity util

---

deploy/prod/main.tf

Enable jira and confluence on prod

---

deploy/dev/main.tf
deploy/prod/main.tf

Signed-off-by: Fayaz G <5818912+fayazg@users.noreply.github.com>

double git connector memory since git onboarding has been enabled (korg)

---

deploy/prod/main.tf

Enable bugzilla, groupsio, pipermail,dockerhub, circleci and jenkins connectors to scheduler

---

utils.go

Add check bot email

---

deploy/dev/main.tf
deploy/prod/main.tf
es.go
go.mod
go.sum
request.go
utils.go

Signed-off-by: Fayaz G <5818912+fayazg@users.noreply.github.com>

match the DL mark_bots.py script

---

deploy/prod/main.tf

Increase github/gerrit memory

---

deploy/dev/main.tf
deploy/prod/main.tf

Add github fetch pages environment variable

---

deploy/dev/main.tf
deploy/prod/main.tf

Add jira and confluence task secrets

---

deploy/dev/main.tf
deploy/prod/main.tf

Add git secrets

---

aws/s3/s3.go
report/README.md
report/manager.go

add report library

---

deploy/dev/main.tf
deploy/prod/main.tf

Add datalake service url to git connector

---

deploy/dev/main.tf
deploy/prod/main.tf
deploy/test/main.tf

closes #104 
Signed-off-by: Ibrahim Mbaziira <dev.code.ibra@gmail.com>

increase jenkins task cpu & memory

---

deploy/dev/main.tf
deploy/prod/main.tf

Increase jira memory

---

deploy/dev/main.tf
deploy/prod/main.tf

Increase confluence memory

---

http/client.go

Add http request with request
